translate portuguese strings:
    old "Self-voicing disabled."
    new "Narração assistiva desabilitada."
    old "Clipboard voicing enabled. "
    new "Narração da área de transferência habilitada. "
    old "Self-voicing enabled. "
    new "Narração assistiva habilitada. "
    old "Accessibility Menu. Use up and down arrows to navigate, and enter to activate buttons and bars."
    new "Menu de Acessibilidade. Navegue usando as setas para cima e para baixo, e Enter para ativar os botões e barras."
    old "Font Override"
    new "Substituição de Fonte"
    old "Default"
    new "Padrão"
    old "DejaVu Sans"
    new "DejaVu Sans"
    old "Opendyslexic"
    new "Opendyslexic"
    old "Text Size Scaling"
    new "Escala do Tamanho do Texto"
    old "Reset"
    new "Resetar"
    old "Line Spacing Scaling"
    new "Escala do Espaçamento entre Linhas"
    old "High Contrast Text"
    new "Texto de Alto Contraste"
    old "Enable"
    new "Habilitar"
    old "Disable"
    new "Desabilitar"
    old "Self-Voicing"
    new "Narração Assistiva"
    old "Self-voicing support is limited when using a touch screen."
    new "O suporte a narração assistiva em telas sensíveis ao toque é limitado."
    old "Off"
    new "Desabilitado"
    old "Text-to-speech"
    new "Texto para Fala"
    old "Clipboard"
    new "Área de Transferência"
    old "Debug"
    new "Depurar"
    old "Self-Voicing Volume Drop"
    new "Redução de Volume da Narração Assistiva"
    old "The options on this menu are intended to improve accessibility. They may not work with all games, and some combinations of options may render the game unplayable. This is not an issue with the game or engine. For the best results when changing fonts, try to keep the text size the same as it originally was."
    new "As opções nesse menu visam melhorar a accessibilidade. Elas não vão funcionar com todos os jogos, e algumas combinações de opções podem deixar o game injogável. Isso não é um problema com o jogo ou a engine. Para melhores resultados mudando fontes, tente manter o tamanho do texto igual ao que era originalmente."
    old "{#weekday}Monday"
    new ""
    old "{#weekday}Tuesday"
    new ""
    old "{#weekday}Wednesday"
    new ""
    old "{#weekday}Thursday"
    new ""
    old "{#weekday}Friday"
    new ""
    old "{#weekday}Saturday"
    new ""
    old "{#weekday}Sunday"
    new ""
    old "{#weekday_short}Mon"
    new ""
    old "{#weekday_short}Tue"
    new ""
    old "{#weekday_short}Wed"
    new ""
    old "{#weekday_short}Thu"
    new ""
    old "{#weekday_short}Fri"
    new ""
    old "{#weekday_short}Sat"
    new ""
    old "{#weekday_short}Sun"
    new ""
    old "{#month}January"
    new ""
    old "{#month}February"
    new ""
    old "{#month}March"
    new ""
    old "{#month}April"
    new ""
    old "{#month}May"
    new ""
    old "{#month}June"
    new ""
    old "{#month}July"
    new ""
    old "{#month}August"
    new ""
    old "{#month}September"
    new ""
    old "{#month}October"
    new ""
    old "{#month}November"
    new ""
    old "{#month}December"
    new ""
    old "{#month_short}Jan"
    new ""
    old "{#month_short}Feb"
    new ""
    old "{#month_short}Mar"
    new ""
    old "{#month_short}Apr"
    new ""
    old "{#month_short}May"
    new ""
    old "{#month_short}Jun"
    new ""
    old "{#month_short}Jul"
    new ""
    old "{#month_short}Aug"
    new ""
    old "{#month_short}Sep"
    new ""
    old "{#month_short}Oct"
    new ""
    old "{#month_short}Nov"
    new ""
    old "{#month_short}Dec"
    new ""
    old "%b %d, %H:%M"
    new ""
    old "Save slot %s: [text]"
    new ""
    old "Load slot %s: [text]"
    new ""
    old "Delete slot [text]"
    new ""
    old "File page auto"
    new ""
    old "File page quick"
    new ""
    old "File page [text]"
    new ""
    old "Next file page."
    new ""
    old "Previous file page."
    new ""
    old "Quick save complete."
    new ""
    old "Quick save."
    new ""
    old "Quick load."
    new ""
    old "Language [text]"
    new ""
    old "Open [text] directory."
    new ""
    old "Are you sure?"
    new ""
    old "Are you sure you want to delete this save?"
    new ""
    old "Are you sure you want to overwrite your save?"
    new ""
    old "Loading will lose unsaved progress.\nAre you sure you want to do this?"
    new ""
    old "Are you sure you want to quit?"
    new ""
    old "Are you sure you want to return to the main menu?\nThis will lose unsaved progress."
    new ""
    old "Are you sure you want to continue where you left off?"
    new ""
    old "Are you sure you want to end the replay?"
    new ""
    old "Are you sure you want to begin skipping?"
    new ""
    old "Are you sure you want to skip to the next choice?"
    new ""
    old "Are you sure you want to skip unseen dialogue to the next choice?"
    new ""
    old "This save was created on a different device. Maliciously constructed save files can harm your computer. Do you trust this save's creator and everyone who could have changed the file?"
    new ""
    old "Do you trust the device the save was created on? You should only choose yes if you are the device's sole user."
    new ""
    old "Failed to save screenshot as %s."
    new ""
    old "Saved screenshot as %s."
    new ""
    old "Skip Mode"
    new ""
    old "This program contains free software under a number of licenses, including the MIT License and GNU Lesser General Public License. A complete list of software, including links to full source code, can be found {a=https://www.renpy.org/l/license}here{/a}."
    new ""
    old "Clipboard voicing enabled. Press 'shift+C' to disable."
    new ""
    old "Self-voicing would say \"[renpy.display.tts.last]\". Press 'alt+shift+V' to disable."
    new ""
    old "Self-voicing enabled. Press 'v' to disable."
    new ""
    old "Renderer"
    new ""
    old "Automatically Choose"
    new ""
    old "Force GL Renderer"
    new ""
    old "Force ANGLE Renderer"
    new ""
    old "Force GLES Renderer"
    new ""
    old "Force GL2 Renderer"
    new ""
    old "Force ANGLE2 Renderer"
    new ""
    old "Force GLES2 Renderer"
    new ""
    old "Enable (No Blocklist)"
    new ""
    old "Powersave"
    new ""
    old "Framerate"
    new ""
    old "Screen"
    new ""
    old "60"
    new ""
    old "30"
    new ""
    old "Tearing"
    new ""
    old "Changes will take effect the next time this program is run."
    new ""
    old "Performance Warning"
    new ""
    old "This computer is using software rendering."
    new ""
    old "This game requires use of GL2 that can't be initialised."
    new ""
    old "This computer has a problem displaying graphics: [problem]."
    new ""
    old "Its graphics drivers may be out of date or not operating correctly. This can lead to slow or incorrect graphics display."
    new ""
    old "The {a=edit:1:log.txt}log.txt{/a} file may contain information to help you determine what is wrong with your computer."
    new ""
    old "More details on how to fix this can be found in the {a=[url]}documentation{/a}."
    new ""
    old "Continue, Show this warning again"
    new ""
    old "Continue, Don't show warning again"
    new ""
    old "Change render options"
    new ""
    old "Select Gamepad to Calibrate"
    new ""
    old "No Gamepads Available"
    new ""
    old "Calibrating [name] ([i]/[total])"
    new ""
    old "Press or move the '[control!s]' [kind]."
    new ""
    old "Skip (A)"
    new ""
    old "Back (B)"
    new ""
    old "Open"
    new ""
    old "Opens the traceback.txt file in a text editor."
    new ""
    old "Copy BBCode"
    new ""
    old "Copies the traceback.txt file to the clipboard as BBcode for forums like https://lemmasoft.renai.us/."
    new ""
    old "Copy Markdown"
    new ""
    old "Copies the traceback.txt file to the clipboard as Markdown for Discord."
    new ""
    old "An exception has occurred."
    new ""
    old "Rollback"
    new ""
    old "Attempts a roll back to a prior time, allowing you to save or choose a different choice."
    new ""
    old "Ignore"
    new ""
    old "Ignores the exception, allowing you to continue."
    new ""
    old "Ignores the exception, allowing you to continue. This often leads to additional errors."
    new ""
    old "Reload"
    new ""
    old "Reloads the game from disk, saving and restoring game state if possible."
    new ""
    old "Console"
    new ""
    old "Opens a console to allow debugging the problem."
    new ""
    old "Quits the game."
    new ""
    old "Parsing the script failed."
    new ""
    old "Back"
    new ""
    old "History"
    new ""
    old "Skip"
    new ""
    old "Auto"
    new ""
    old "Save"
    new ""
    old "Q.Save"
    new ""
    old "Q.Load"
    new ""
    old "Prefs"
    new ""
    old "Load"
    new ""
    old "Preferences"
    new ""
    old "Gallery"
    new ""
    old "About"
    new ""
    old "Help"
    new ""
    old "End Replay"
    new ""
    old "Main Menu"
    new ""
    old "Quit"
    new ""
    old "Return"
    new ""
    old "Version [config.version!t]\n"
    new ""
    old "Made with {a=https://www.renpy.org/}Ren'Py{/a} [renpy.version_only].\n\n[renpy.license!t]"
    new ""
    old "Page {}"
    new ""
    old "Automatic saves"
    new ""
    old "Quick saves"
    new ""
    old "{#file_time}%A, %B %d %Y, %H:%M"
    new ""
    old "empty slot"
    new ""
    old "<"
    new ""
    old "{#auto_page}A"
    new ""
    old "{#quick_page}Q"
    new ""
    old ">"
    new ""
    old "Upload Sync"
    new ""
    old "Download Sync"
    new ""
    old "Display"
    new ""
    old "Window"
    new ""
    old "Fullscreen"
    new ""
    old "Unseen Text"
    new ""
    old "After Choices"
    new ""
    old "Transitions"
    new ""
    old "Dialogue box opacity"
    new ""
    old "Text Speed"
    new ""
    old "Auto-Forward Time"
    new ""
    old "Music Volume"
    new ""
    old "Sound Volume"
    new ""
    old "Test"
    new ""
    old "Voice Volume"
    new ""
    old "Mute All"
    new ""
    old "The dialogue history is empty."
    new ""
    old "Keyboard"
    new ""
    old "Mouse"
    new ""
    old "Gamepad"
    new ""
    old "Enter"
    new ""
    old "Advances dialogue and activates the interface."
    new ""
    old "Space"
    new ""
    old "Advances dialogue without selecting choices."
    new ""
    old "Arrow Keys"
    new ""
    old "Navigate the interface."
    new ""
    old "Escape"
    new ""
    old "Accesses the game menu."
    new ""
    old "Ctrl"
    new ""
    old "Skips dialogue while held down."
    new ""
    old "Tab"
    new ""
    old "Toggles dialogue skipping."
    new ""
    old "Page Up"
    new ""
    old "Rolls back to earlier dialogue."
    new ""
    old "Page Down"
    new ""
    old "Rolls forward to later dialogue."
    new ""
    old "Hides the user interface."
    new ""
    old "Takes a screenshot."
    new ""
    old "Toggles assistive {a=https://www.renpy.org/l/voicing}self-voicing{/a}."
    new ""
    old "Opens the accessibility menu."
    new ""
    old "Left Click"
    new ""
    old "Middle Click"
    new ""
    old "Right Click"
    new ""
    old "Mouse Wheel Up"
    new ""
    old "Mouse Wheel Down"
    new ""
    old "Right Trigger\nA/Bottom Button"
    new ""
    old "Left Trigger\nLeft Shoulder"
    new ""
    old "Right Shoulder"
    new ""
    old "D-Pad, Sticks"
    new ""
    old "Start, Guide, B/Right Button"
    new ""
    old "Y/Top Button"
    new ""
    old "Calibrate"
    new ""
    old "Yes"
    new ""
    old "No"
    new ""
    old "Skipping"
    new ""
    old "Menu"
    new ""
    old "F.A.Q."
    new ""
    old "{color=#305876}Q{/color}: What fetishes can we expect in your game?"
    new ""
    old "{color=#00dcd3}A{/color}: Harem ending, virgins (All love interests in all my games will be virgins or have been deflowered by the {b}protagonist{/b}. No exceptions.), deflowering (Blood is optional), pregnancy, MFF+F+F+(ad infinitum), lactation (Optional), titfucking, anal (Optional), watersports (Optional), footjob (Optional) and hardcore handholding. The list can grow so feel free to suggest anything that isn't encompased on my \"I'll never add list\"."
    new ""
    old "{color=#305876}Q{/color}: So, what's that \"I'll never add list\"?"
    new ""
    old "{color=#00dcd3}A{/color}: I will {color=#FF0000}NEVER{/color} add: bestiality, rape, scat, sharing/swinging, ntr, any form of \"technically not ntr\", guro, exhibitionism, voyeur, loli/shota, femdom, males and/or penises other than the protagonist, any form of \"it's techniaclly not___\" related to any of these. This list can grow too since there's many obscure fetishes out there which I'm not aware of."
    new ""
    old "{color=#305876}Q{/color}:Why have these big lists?"
    new ""
    old "{color=#00dcd3}A{/color}:Transparency. I don't want to waste your time and resources believing you'll be free of certain contents (wether optional or not) or that you'll find certain content which I'd never add."
    new ""
    old "{color=#305876}Q{/color}:Was Paranormalia abandoned?"
    new ""
    old "{color=#00dcd3}A{/color}:No. I decided to delay it since it would take years to finish it since my initial plan was too big. I don't want to milk the same game for decades. I've decided to rewrite it and cut the \"excess fat\". This is why I made the SnS to give me some breathing room and to give you guys something in the meantime. I'll continue working on it on the background as I finish this SnS."
    new ""
    old "{color=#305876}Q{/color}:What are Sexpansions? Are they canon?"
    new ""
    old "{color=#00dcd3}A{/color}:They're extra sex scene that I've cooked up but won't end up in the main storyline. They aren't story sensitive and they happen between time jumps. Wether they happen or not depends on which fetish you like/dislike. Don't like anal? Then that scene never happened."
    new ""
    old "SnS_My catgirl harem"
    new ""
    old "\nPortuguese translation by {a=https://allmylinks.com/defm64}defm64{/a}.\nLicensed under {a=https://creativecommons.org/licenses/by-nc-sa/4.0/}CC BY-NC-SA 4.0{/a}."
    new ""
    old "Language"
    new ""
    old "I am 18 or older."
    new ""
    old "I am under 18."
    new ""
    old "Continue fingering Amber a little longer."
    new ""
    old "Make her cum"
    new ""
    old "Hold on a little longer."
    new ""
    old "Creampie her!"
    new ""
    old "Suck your [title]'s dick"
    new ""
    old "Spread your cute little pussy for me."
    new ""
    old "Hold on a little more."
    new ""
    old "Fill her tummy."
    new ""
    old "Eat Amber's cute little pussy."
    new ""
    old "Breed your little kitty."
    new ""
    old "Finger her ass."
    new ""
    old "Finger her pussy"
    new ""
    old "Continue Eating Amber out."
    new ""
    old "Tell your kitty to suck your cock."
    new ""
    old "Continue playing with Amber's ass."
    new ""
    old "Breed your little kitty"
    new ""
    old "Creampie your kitty."
    new ""
    old "Return to the Main Menu."
    new ""
    old "Send me to the Gallery"
    new ""
    old "Send me to the Patreon"
    new ""
    old "Credits"
    new ""
