translate portuguese strings:
    old "Self-voicing disabled."
    new "Narração assistiva desabilitada."
    old "Clipboard voicing enabled. "
    new "Narração da área de transferência habilitada. "
    old "Self-voicing enabled. "
    new "Narração assistiva habilitada. "
    old "Accessibility Menu. Use up and down arrows to navigate, and enter to activate buttons and bars."
    new "Menu de Acessibilidade. Navegue usando as setas para cima e para baixo, e Enter para ativar os botões e barras."
    old "Font Override"
    new "Substituição de Fonte"
    old "Default"
    new "Padrão"
    old "DejaVu Sans"
    new "DejaVu Sans"
    old "Opendyslexic"
    new "Opendyslexic"
    old "Text Size Scaling"
    new "Escala do Tamanho do Texto"
    old "Reset"
    new "Resetar"
    old "Line Spacing Scaling"
    new "Escala do Espaçamento entre Linhas"
    old "High Contrast Text"
    new "Texto de Alto Contraste"
    old "Enable"
    new "Habilitar"
    old "Disable"
    new "Desabilitar"
    old "Self-Voicing"
    new "Narração Assistiva"
    old "Self-voicing support is limited when using a touch screen."
    new "O suporte a narração assistiva em telas sensíveis ao toque é limitado."
    old "Off"
    new "Desabilitado"
    old "Text-to-speech"
    new "Texto para Fala"
    old "Clipboard"
    new "Área de Transferência"
    old "Debug"
    new "Depurar"
    old "Self-Voicing Volume Drop"
    new "Redução de Volume da Narração Assistiva"
    old "The options on this menu are intended to improve accessibility. They may not work with all games, and some combinations of options may render the game unplayable. This is not an issue with the game or engine. For the best results when changing fonts, try to keep the text size the same as it originally was."
    new "As opções nesse menu visam melhorar a accessibilidade. Elas não vão funcionar com todos os jogos, e algumas combinações de opções podem deixar o game injogável. Isso não é um problema com o jogo ou a engine. Para melhores resultados mudando fontes, tente manter o tamanho do texto igual ao que era originalmente."
    old "{#weekday}Monday"
    new "{#weekday}Segunda"
    old "{#weekday}Tuesday"
    new "{#weekday}Terça"
    old "{#weekday}Wednesday"
    new "{#weekday}Quarta"
    old "{#weekday}Thursday"
    new "{#weekday}Quinta"
    old "{#weekday}Friday"
    new "{#weekday}Sexta"
    old "{#weekday}Saturday"
    new "{#weekday}Sábado"
    old "{#weekday}Sunday"
    new "{#weekday}Domingo"
    old "{#weekday_short}Mon"
    new "{#weekday_short}Seg"
    old "{#weekday_short}Tue"
    new "{#weekday_short}Ter"
    old "{#weekday_short}Wed"
    new "{#weekday_short}Qua"
    old "{#weekday_short}Thu"
    new "{#weekday_short}Qui"
    old "{#weekday_short}Fri"
    new "{#weekday_short}Sex"
    old "{#weekday_short}Sat"
    new "{#weekday_short}Sáb"
    old "{#weekday_short}Sun"
    new "{#weekday_short}Dom"
    old "{#month}January"
    new "{#month}Janeiro"
    old "{#month}February"
    new "{#month}Fevereiro"
    old "{#month}March"
    new "{#month}Março"
    old "{#month}April"
    new "{#month}Abril"
    old "{#month}May"
    new "{#month}Maio"
    old "{#month}June"
    new "{#month}Junho"
    old "{#month}July"
    new "{#month}Julho"
    old "{#month}August"
    new "{#month}Agosto"
    old "{#month}September"
    new "{#month}Setembro"
    old "{#month}October"
    new "{#month}Outubro"
    old "{#month}November"
    new "{#month}Novembro"
    old "{#month}December"
    new "{#month}Dezembro"
    old "{#month_short}Jan"
    new "{#month_short}Jan"
    old "{#month_short}Feb"
    new "{#month_short}Fev"
    old "{#month_short}Mar"
    new "{#month_short}Mar"
    old "{#month_short}Apr"
    new "{#month_short}Abr"
    old "{#month_short}May"
    new "{#month_short}Mai"
    old "{#month_short}Jun"
    new "{#month_short}Jun"
    old "{#month_short}Jul"
    new "{#month_short}Jul"
    old "{#month_short}Aug"
    new "{#month_short}Ago"
    old "{#month_short}Sep"
    new "{#month_short}Set"
    old "{#month_short}Oct"
    new "{#month_short}Out"
    old "{#month_short}Nov"
    new "{#month_short}Nov"
    old "{#month_short}Dec"
    new "{#month_short}Dez"
    old "%b %d, %H:%M"
    new "%d %b, %H:%M"
    old "Save slot %s: [text]"
    new "Salvar no slot %s: [text]"
    old "Load slot %s: [text]"
    new "Carregar slot %s: [text]"
    old "Delete slot [text]"
    new "Deletar slot [text]"
    old "File page auto"
    new "Página do arquivo (s. auto)"
    old "File page quick"
    new "Página do arquivo (s. rápido)"
    old "File page [text]"
    new "Página [text] do arquivo"
    old "Next file page."
    new "Página seguinte do arquivo."
    old "Previous file page."
    new "Página anterior do arquivo."
    old "Quick save complete."
    new "Salvamento rápido concluído."
    old "Quick save."
    new "Salvamento rápido."
    old "Quick load."
    new "Carregamento rápido."
    old "Language [text]"
    new "Idioma [text]"
    old "Open [text] directory."
    new "Abrir diretório [text]."
    old "Are you sure?"
    new "Você tem certeza?"
    old "Are you sure you want to delete this save?"
    new "Você tem certeza que deseja deletar este save?"
    old "Are you sure you want to overwrite your save?"
    new "Você tem certeza que deseja sobrescrever este save?"
    old "Loading will lose unsaved progress.\nAre you sure you want to do this?"
    new "Ao carregar, qualquer progresso não salvo será perdido.\nVocê tem certeza que deseja fazer isso?"
    old "Are you sure you want to quit?"
    new "Você tem certeza que deseja sair?"
    old "Are you sure you want to return to the main menu?\nThis will lose unsaved progress."
    new "Você tem certeza que deseja voltar para o menu principal?\nQualquer progresso não salvo será perdido."
    old "Are you sure you want to continue where you left off?"
    new "Você tem certeza de que deseja continuar de onde parou?"
    old "Are you sure you want to end the replay?"
    new "Você tem certeza que deseja encerrar o replay?"
    old "Are you sure you want to begin skipping?"
    new "Você tem certeza que deseja começar a pular o diálogo?"
    old "Are you sure you want to skip to the next choice?"
    new "Você tem certeza que deseja pular o diálogo até a próxima escolha?"
    old "Are you sure you want to skip unseen dialogue to the next choice?"
    new "Você tem certeza que deseja pular o diálogo ainda não visto até a próxima escolha?"
    old "This save was created on a different device. Maliciously constructed save files can harm your computer. Do you trust this save's creator and everyone who could have changed the file?"
    new "Este save foi criado em um outro dispositivo. Arquivos de save maliciosos podem colocar seu computador em risco. O criador do save e qualquer um que tenha modificado este arquivo são confiáveis?"
    old "Do you trust the device the save was created on? You should only choose yes if you are the device's sole user."
    new "O dispositivo que criou o save é confiável? Só escolha sim se você for o único usuário deste dispositivo."
    old "Failed to save screenshot as %s."
    new "Falha ao salvar captura de tela em %s."
    old "Saved screenshot as %s."
    new "Captura de tela salva em %s."
    old "Skip Mode"
    new "Modo de Pulo de Diálogo"
    old "This program contains free software under a number of licenses, including the MIT License and GNU Lesser General Public License. A complete list of software, including links to full source code, can be found {a=https://www.renpy.org/l/license}here{/a}."
    new "Este programa contém software livre sob diferentes licenças, incluindo a Licença MIT e a GNU LGPL. A lista completa dos softwares, incluindo links para o código fonte completo, pode ser encontrado {a=https://www.renpy.org/l/license}aqui{/a}."
    old "Clipboard voicing enabled. Press 'shift+C' to disable."
    new "Narração da área de transferência habilitada. Pressione 'Shift+C' para desabilitar."
    old "Self-voicing would say \"[renpy.display.tts.last]\". Press 'alt+shift+V' to disable."
    new "A narração assistiva diria \"[renpy.display.tts.last]\". Pressione 'Alt+Shift+V' para desabilitar."
    old "Self-voicing enabled. Press 'v' to disable."
    new "Narração assistiva habilitada. Pressione 'V' para desabilitar."
    old "Renderer"
    new "Renderizador"
    old "Automatically Choose"
    new "Escolher Automaticamente"
    old "Force GL Renderer"
    new "Forçar Renderizador GL"
    old "Force ANGLE Renderer"
    new "Forçar Renderizador ANGLE"
    old "Force GLES Renderer"
    new "Forçar Renderizador GLES"
    old "Force GL2 Renderer"
    new "Forçar Renderizador GL2"
    old "Force ANGLE2 Renderer"
    new "Forçar Renderizador ANGLE2"
    old "Force GLES2 Renderer"
    new "Forçar Renderizador GLES2"
    old "Enable (No Blocklist)"
    new "Habilitar (Sem Lista de Bloqueio)"
    old "Powersave"
    new "Economia de Energia"
    old "Framerate"
    new "Taxa de Quadros"
    old "Screen"
    new "Máximo Suportado pela Tela"
    old "60"
    new "60"
    old "30"
    new "30"
    old "Tearing"
    new "Tearing"
    old "Changes will take effect the next time this program is run."
    new "As alterações serão aplicadas na próxima vez que este jogo for executado."
    old "Performance Warning"
    new "Aviso de Performance"
    old "This computer is using software rendering."
    new "Este dispositivo está usando renderização via software."
    old "This game requires use of GL2 that can't be initialised."
    new "Este jogo requer o uso de GL2, que não pode ser inicializado."
    old "This computer has a problem displaying graphics: [problem]."
    new "Este dispositivo está com um problema na exibição de gráficos: [problem]."
    old "Its graphics drivers may be out of date or not operating correctly. This can lead to slow or incorrect graphics display."
    new "Os drivers gráficos podem estar desatualizados ou sem funcionar direito. Isso pode causar lentidão ou uma exibição incorreta dos gráficos."
    old "The {a=edit:1:log.txt}log.txt{/a} file may contain information to help you determine what is wrong with your computer."
    new "O arquivo {a=edit:1:log.txt}log.txt{/a} pode conter informações que ajudarão a determinar o que há de errado com seu dispositivo."
    old "More details on how to fix this can be found in the {a=[url]}documentation{/a}."
    new "Mais detalhes sobre como corrigir isso podem ser encontrados na {a=[url]}documentação{/a}."
    old "Continue, Show this warning again"
    new "Continuar, Mostrar este aviso novamente"
    old "Continue, Don't show warning again"
    new "Continuar, Não mostrar este aviso novamente"
    old "Change render options"
    new "Alterar opções de renderização"
    old "Select Gamepad to Calibrate"
    new "Selecione o Controle para Calibrar"
    old "No Gamepads Available"
    new "Não há Controles Disponíveis"
    old "Calibrating [name] ([i]/[total])"
    new "Calibrando [name] ([i]/[total])"
    old "Press or move the '[control!s]' [kind]."
    new "Pressione ou movimente os [kind] '[control!s]'"
    old "Skip (A)"
    new "Pular (A)"
    old "Back (B)"
    new "Voltar (B)"
    old "Open"
    new "Abrir"
    old "Opens the traceback.txt file in a text editor."
    new "Abre o arquivo traceback.txt em um editor de texto."
    old "Copy BBCode"
    new "Copiar BBCode"
    old "Copies the traceback.txt file to the clipboard as BBcode for forums like https://lemmasoft.renai.us/."
    new "Copia o arquivo traceback.txt para a área de transferência como BBcode para fóruns como https://lemmasoft.renai.us/."
    old "Copy Markdown"
    new "Copiar Markdown"
    old "Copies the traceback.txt file to the clipboard as Markdown for Discord."
    new "Copia o arquivo traceback.txt para a área de transferência como Markdown para o Discord."
    old "An exception has occurred."
    new "Ocorreu uma exceção."
    old "Rollback"
    new "Rollback"
    old "Attempts a roll back to a prior time, allowing you to save or choose a different choice."
    new "Tenta dar rollback para um momento anterior, permitindo que você salve ou faça uma escolha diferente."
    old "Ignore"
    new "Ignorar"
    old "Ignores the exception, allowing you to continue."
    new "Ignora a exceção, permitindo que você continue."
    old "Ignores the exception, allowing you to continue. This often leads to additional errors."
    new "Ignora a exceção, permitindo que você continue. Isso costuma causar erros adicionais."
    old "Reload"
    new "Recarregar"
    old "Reloads the game from disk, saving and restoring game state if possible."
    new "Recarrega os arquivos do jogo do armazenamento, salvando e restaurando o estado do jogo se possível."
    old "Console"
    new "Console"
    old "Opens a console to allow debugging the problem."
    new "Abre um console para permitir depurar o problema."
    old "Quits the game."
    new "Fecha o jogo."
    old "Parsing the script failed."
    new "A interpretação do script falhou."
    old "Back"
    new "Voltar"
    old "History"
    new "Histórico"
    old "Skip"
    new "Pular"
    old "Auto"
    new "Modo Auto"
    old "Save"
    new "Salvar"
    old "Q.Save"
    new "Salvar Rápido"
    old "Q.Load"
    new "Carregar Rápido"
    old "Prefs"
    new "Preferências"
    old "Load"
    new "Carregar"
    old "Preferences"
    new "Preferências"
    old "Gallery"
    new "Galeria"
    old "About"
    new "Sobre"
    old "Help"
    new "Ajuda"
    old "End Replay"
    new "Encerrar Replay"
    old "Main Menu"
    new "Menu Principal"
    old "Quit"
    new "Sair"
    old "Return"
    new "Voltar"
    old "Version [config.version!t]\n"
    new "Versão [config.version!t]\n"
    old "Made with {a=https://www.renpy.org/}Ren'Py{/a} [renpy.version_only].\n\n[renpy.license!t]"
    new "Feito com {a=https://www.renpy.org/}Ren'Py{/a} [renpy.version_only].\n\n[renpy.license!t]"
    old "Page {}"
    new "Página {}"
    old "Automatic saves"
    new "Saves automáticos"
    old "Quick saves"
    new "Saves rápidos"
    old "{#file_time}%A, %B %d %Y, %H:%M"
    new "{#file_time}%A, %d de %B de %Y, %H:%M"
    old "empty slot"
    new "slot vazio"
    old "<"
    new "<"
    old "{#auto_page}A"
    new "{#auto_page}A"
    old "{#quick_page}Q"
    new "{#quick_page}R"
    old ">"
    new ">"
    old "Upload Sync"
    new ""
    old "Download Sync"
    new ""
    old "Display"
    new ""
    old "Window"
    new ""
    old "Fullscreen"
    new ""
    old "Unseen Text"
    new ""
    old "After Choices"
    new ""
    old "Transitions"
    new ""
    old "Dialogue box opacity"
    new ""
    old "Text Speed"
    new ""
    old "Auto-Forward Time"
    new ""
    old "Music Volume"
    new ""
    old "Sound Volume"
    new ""
    old "Test"
    new ""
    old "Voice Volume"
    new ""
    old "Mute All"
    new ""
    old "The dialogue history is empty."
    new ""
    old "Keyboard"
    new ""
    old "Mouse"
    new ""
    old "Gamepad"
    new ""
    old "Enter"
    new ""
    old "Advances dialogue and activates the interface."
    new ""
    old "Space"
    new ""
    old "Advances dialogue without selecting choices."
    new ""
    old "Arrow Keys"
    new ""
    old "Navigate the interface."
    new ""
    old "Escape"
    new ""
    old "Accesses the game menu."
    new ""
    old "Ctrl"
    new ""
    old "Skips dialogue while held down."
    new ""
    old "Tab"
    new ""
    old "Toggles dialogue skipping."
    new ""
    old "Page Up"
    new ""
    old "Rolls back to earlier dialogue."
    new ""
    old "Page Down"
    new ""
    old "Rolls forward to later dialogue."
    new ""
    old "Hides the user interface."
    new ""
    old "Takes a screenshot."
    new ""
    old "Toggles assistive {a=https://www.renpy.org/l/voicing}self-voicing{/a}."
    new ""
    old "Opens the accessibility menu."
    new ""
    old "Left Click"
    new ""
    old "Middle Click"
    new ""
    old "Right Click"
    new ""
    old "Mouse Wheel Up"
    new ""
    old "Mouse Wheel Down"
    new ""
    old "Right Trigger\nA/Bottom Button"
    new ""
    old "Left Trigger\nLeft Shoulder"
    new ""
    old "Right Shoulder"
    new ""
    old "D-Pad, Sticks"
    new ""
    old "Start, Guide, B/Right Button"
    new ""
    old "Y/Top Button"
    new ""
    old "Calibrate"
    new ""
    old "Yes"
    new ""
    old "No"
    new ""
    old "Skipping"
    new ""
    old "Menu"
    new ""
    old "F.A.Q."
    new ""
    old "{color=#305876}Q{/color}: What fetishes can we expect in your game?"
    new ""
    old "{color=#00dcd3}A{/color}: Harem ending, virgins (All love interests in all my games will be virgins or have been deflowered by the {b}protagonist{/b}. No exceptions.), deflowering (Blood is optional), pregnancy, MFF+F+F+(ad infinitum), lactation (Optional), titfucking, anal (Optional), watersports (Optional), footjob (Optional) and hardcore handholding. The list can grow so feel free to suggest anything that isn't encompased on my \"I'll never add list\"."
    new ""
    old "{color=#305876}Q{/color}: So, what's that \"I'll never add list\"?"
    new ""
    old "{color=#00dcd3}A{/color}: I will {color=#FF0000}NEVER{/color} add: bestiality, rape, scat, sharing/swinging, ntr, any form of \"technically not ntr\", guro, exhibitionism, voyeur, loli/shota, femdom, males and/or penises other than the protagonist, any form of \"it's techniaclly not___\" related to any of these. This list can grow too since there's many obscure fetishes out there which I'm not aware of."
    new ""
    old "{color=#305876}Q{/color}:Why have these big lists?"
    new ""
    old "{color=#00dcd3}A{/color}:Transparency. I don't want to waste your time and resources believing you'll be free of certain contents (wether optional or not) or that you'll find certain content which I'd never add."
    new ""
    old "{color=#305876}Q{/color}:Was Paranormalia abandoned?"
    new ""
    old "{color=#00dcd3}A{/color}:No. I decided to delay it since it would take years to finish it since my initial plan was too big. I don't want to milk the same game for decades. I've decided to rewrite it and cut the \"excess fat\". This is why I made the SnS to give me some breathing room and to give you guys something in the meantime. I'll continue working on it on the background as I finish this SnS."
    new ""
    old "{color=#305876}Q{/color}:What are Sexpansions? Are they canon?"
    new ""
    old "{color=#00dcd3}A{/color}:They're extra sex scene that I've cooked up but won't end up in the main storyline. They aren't story sensitive and they happen between time jumps. Wether they happen or not depends on which fetish you like/dislike. Don't like anal? Then that scene never happened."
    new ""
    old "SnS_My catgirl harem"
    new ""
    old "\nPortuguese translation by {a=https://allmylinks.com/defm64}defm64{/a}.\nLicensed under {a=https://creativecommons.org/licenses/by-nc-sa/4.0/}CC BY-NC-SA 4.0{/a}."
    new ""
    old "Language"
    new ""
    old "I am 18 or older."
    new ""
    old "I am under 18."
    new ""
    old "Continue fingering Amber a little longer."
    new ""
    old "Make her cum"
    new ""
    old "Hold on a little longer."
    new ""
    old "Creampie her!"
    new ""
    old "Suck your [title]'s dick"
    new ""
    old "Spread your cute little pussy for me."
    new ""
    old "Hold on a little more."
    new ""
    old "Fill her tummy."
    new ""
    old "Eat Amber's cute little pussy."
    new ""
    old "Breed your little kitty."
    new ""
    old "Finger her ass."
    new ""
    old "Finger her pussy"
    new ""
    old "Continue Eating Amber out."
    new ""
    old "Tell your kitty to suck your cock."
    new ""
    old "Continue playing with Amber's ass."
    new ""
    old "Breed your little kitty"
    new ""
    old "Creampie your kitty."
    new ""
    old "Return to the Main Menu."
    new ""
    old "Send me to the Gallery"
    new ""
    old "Send me to the Patreon"
    new ""
    old "Credits"
    new ""
